# Generated by Django 4.0.4 on 2022-05-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_solicitud',
            name='Flag_requiere_documento',
            field=models.BooleanField(default=True),
        ),
    ]
