# Generated by Django 4.0.4 on 2022-05-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citacion',
            options={'verbose_name': 'Citacion', 'verbose_name_plural': 'Citaciones'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tamanio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
