# Generated by Django 4.0.4 on 2022-05-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0002_alter_historico_solicitud_flag_requiere_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion_solicitud_persona',
            name='Tipo_cliente_Id',
        ),
    ]
