# Generated by Django 4.0.4 on 2022-05-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0002_alter_citacion_options_alter_documento_tamanio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hechos',
            options={'verbose_name': 'Hechos', 'verbose_name_plural': 'Hechos'},
        ),
        migrations.AlterModelOptions(
            name='historico_solicitud',
            options={'verbose_name': 'Historico_solicitud', 'verbose_name_plural': 'Historico_solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='medio_conocimiento',
            options={'verbose_name': 'Medio_conocimiento ', 'verbose_name_plural': 'Medios_conocimiento'},
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='Medio_conocimiento_Id',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Medio_conocimiento_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiConciliacionApp.medio_conocimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='Usuario_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiConciliacionApp.usuario'),
        ),
    ]
