# Generated by Django 4.0.4 on 2022-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0008_alter_area_nombre_alter_barrio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medio_conocimiento',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medio_conocimiento',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='objetivo_servicio',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='objetivo_servicio',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pais',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rol',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tema',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_cargo',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_cargo',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_cliente',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_cliente',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_estado',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_estado',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_medio',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_medio',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_persona',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_persona',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_resultado',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_resultado',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_servicio',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_servicio',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipo_vivienda',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_vivienda',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='turno',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
