# Generated by Django 4.0.4 on 2022-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiConciliacionApp', '0009_alter_area_id_alter_area_nombre_alter_barrio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='Nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
