from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()

router.register(r'paises',PaisViewSet,basename='Paises'),
router.register(r'departamentos',DepartamentoViewSet,basename='Departamento')
router.register(r'ciudades',CiudadViewSet,basename='Ciudad')
router.register(r'localidades',LocalidadViewSet,basename='Localidad')
router.register(r'barrios',BarrioViewSet,basename='Barrio')
router.register(r'personas',PersonaViewSet,basename='Persona')
router.register(r'estratos socioeconomicos',Estrato_socioeconomicoViewSet,basename='Estrato_socioeconomico')
router.register(r'tipos_persona',Tipo_personaViewSet,basename='Tipo_persona')
router.register(r'tipos_cargo',Tipo_cargoViewSet,basename='Tipo_cargo')
router.register(r'tipos_documento',Tipo_documentoViewSet,basename='Tipo_documento')
router.register(r'tipos_vivienda',Tipo_viviendaViewSet,basename='Tipo_vivienda')
router.register(r'usuarios',UsuarioViewSet,basename='Usuario')
router.register(r'roles',RolViewSet,basename='Rol')
router.register(r'rol_permisos',Rol_permisoViewSet,basename='Rol_permiso')
router.register(r'perfil',PerfilViewSet,basename='Perfil')
router.register(r'relaciones_area_perfil',Relacion_area_perfilViewSet,basename='Relacion_area_perfil')
router.register(r'areas',AreaViewSet,basename='Area')
router.register(r'hechos',HechosViewSet,basename='Hechos')
router.register(r'solicitudes',SolicitudViewSet,basename='Solicitud')
router.register(r'tipos_resultado',Tipo_resultadoViewSet,basename='Tipo_resultado')
router.register(r'tipos_servicio',Tipo_servicioViewSet,basename='Tipo_servicio')
router.register(r'objetivos_servicio',Objetivo_servicioViewSet,basename='Objetivo_servicio')
router.register(r'subtemas',SubtemaViewSet,basename='Subtema')
router.register(r'temas',TemaViewSet,basename='Tema')
router.register(r'documentos',DocumentoViewSet,basename='Documento')
router.register(r'tipos_estado',Tipo_estadoViewSet,basename='Tipo_estado')
router.register(r'citaciones',CitacionViewSet,basename='Tipo_estado')
router.register(r'historico_solicitudes',Historico_solicitudViewSet,basename='Historico_solicitud')
router.register(r'relaciones_citacion_persona',Relacion_citacion_personaViewSet,basename='Relacion_citacion_persona')
router.register(r'tipos_medio',Tipo_medioViewSet,basename='Tipo_Medio')
router.register(r'turnos',TurnoViewSet,basename='Turno')
router.register(r'tipo_cliente',Tipo_clienteViewSet,basename='Tipo_cliente')
router.register(r'preguntas',PreguntaViewSet,basename='Preguntas')
router.register(r'medio_conocimiento',Medio_conocimientoViewSet,basename='Medio_conocimiento')
router.register(r'Encuesta',EncuestaViewSet,basename='Encuesta')
router.register(r'Respuesta',RespuestaViewSet,basename='Respuesta')
router.register(r'relaciones_solicitud_persona',Relacion_solicitud_personaViewSet,basename='Relacion_solicitud_persona')
urlpatterns = router.urls
