# Generated by Django 4.0.4 on 2022-11-18 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('lugar_expedicion', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('enlace', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_sesion', models.DateField()),
            ],
            options={
                'verbose_name': 'Citacion',
                'verbose_name_plural': 'Citaciones',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_civil',
                'verbose_name_plural': 'Estados_civiles',
            },
        ),
        migrations.CreateModel(
            name='Estrato_socioeconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estrato_socioeconomico',
                'verbose_name_plural': 'Estratos_socioeconomicos',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('año', models.CharField(auto_created=True, default=2022, max_length=4)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('numero_caso', models.PositiveIntegerField()),
                ('fecha_registro', models.DateField()),
                ('caso_gratuito', models.BooleanField(blank=True, default=True, null=True)),
                ('asunto_juridico_definible', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('expediente_pre_cerrado', models.BooleanField(blank=True, default=False, null=True)),
                ('expediente_cerrado', models.BooleanField(blank=True, default=False, null=True)),
                ('area_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.area')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Grupo_etnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo_etnico',
                'verbose_name_plural': 'Grupos_etnicos',
            },
        ),
        migrations.CreateModel(
            name='Inicio_conflicto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Inicio_conflicto',
                'verbose_name_plural': 'Inicios_conflicto',
            },
        ),
        migrations.CreateModel(
            name='Medio_conocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Medio_conocimiento',
                'verbose_name_plural': 'Medios_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Medio_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Medio_seguimiento',
                'verbose_name_plural': 'Medios_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Objetivo_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Objetivo_servicio',
                'verbose_name_plural': 'Objetivos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiExpedientesApp.area')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=25)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=25, null=True)),
                ('apoderado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.apoderado')),
                ('barrio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.barrio')),
                ('ciudad_nacimiento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad')),
                ('escolaridad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.escolaridad')),
                ('estado_civil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_civil')),
                ('estrato_socioeconomico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estrato_socioeconomico')),
                ('genero_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.genero')),
                ('grupo_etnico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.grupo_etnico')),
                ('perfil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.perfil')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pregunta_encuesta',
                'verbose_name_plural': 'Preguntas_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta_seguimiento',
                'verbose_name_plural': 'Preguntas_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Solicitante_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Solicitante_servicio',
                'verbose_name_plural': 'Solicitantes_servicio',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_cargo',
                'verbose_name_plural': 'Tipos_cargo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_cliente',
                'verbose_name_plural': 'Tipos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Tipo_discapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_Discapacidad',
                'verbose_name_plural': 'Tipos_Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_documento',
                'verbose_name_plural': 'Tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_medio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_medio',
                'verbose_name_plural': 'Tipos_medio',
            },
        ),
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_persona',
                'verbose_name_plural': 'Tipos_persona',
            },
        ),
        migrations.CreateModel(
            name='Tipo_reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_reporte',
                'verbose_name_plural': 'Tipos_reporte',
            },
        ),
        migrations.CreateModel(
            name='Tipo_resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('consecutivo_actual', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Tipo_resultado',
                'verbose_name_plural': 'Tipos_resultado',
            },
        ),
        migrations.CreateModel(
            name='Tipo_vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_vivienda',
                'verbose_name_plural': 'Tipos_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('Objetivo_servicio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.objetivo_servicio')),
            ],
            options={
                'verbose_name': 'Tipo_servicio',
                'verbose_name_plural': 'Tipos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tema')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField()),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('medio_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_seguimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('acuerdo', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='resultados/')),
                ('fecha', models.DateField(auto_now=True)),
                ('expediente_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('tipo_resultado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_resultado')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('si_o_no', models.BooleanField()),
                ('porque', models.TextField(blank=True, null=True)),
                ('pregunta_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_seguimiento')),
                ('seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.seguimiento')),
            ],
            options={
                'verbose_name': 'Respuesta_seguimiento',
                'verbose_name_plural': 'Respuestas_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('encuesta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.encuesta')),
                ('pregunta_encuesta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta_encuesta',
                'verbose_name_plural': 'Respuestas_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona')),
                ('tipo_cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cliente')),
            ],
            options={
                'verbose_name': 'Relacion_persona_expediente',
                'verbose_name_plural': 'Relaciones_persona_expediente',
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('citacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.citacion')),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona')),
            ],
            options={
                'verbose_name': 'Relacion_persona_citacion',
                'verbose_name_plural': 'Relaciones_persona_citacion',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.sexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_cargo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cargo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_discapacidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_discapacidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vivienda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_vivienda'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuarioId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado')),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('cuantia_indeterminada', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_interviene_tercero', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_violencia', models.BooleanField(blank=True, default=False, null=True)),
                ('cuantia', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('Flag_conflicto_por_incapacidad', models.BooleanField(blank=True, default=False, null=True)),
                ('pretension', models.TextField(blank=True, null=True)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_resultado')),
                ('expediente_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Hechos',
                'verbose_name_plural': 'Hechos',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='inicio_conflicto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.inicio_conflicto'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitante_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.solicitante_servicio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='subtema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.subtema'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_servicio'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='expediente_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='medio_conocimiento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_conocimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='persona_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('pais_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.departamento'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='expediente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='tipo_medio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_medio'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='turnos_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.turno'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='localidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.localidad'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='tipo_documento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento'),
        ),
        migrations.AddConstraint(
            model_name='expediente',
            constraint=models.UniqueConstraint(fields=('numero_caso', 'año'), name='caso_por_año'),
        ),
    ]
