# Generated by Django 4.1.3 on 2022-11-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('lugar_expedicion', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Datos_estudio',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Datos_estudio',
                'verbose_name_plural': 'Datos_estudio',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado_civil',
                'verbose_name_plural': 'Estados_civiles',
            },
        ),
        migrations.CreateModel(
            name='Estrato_socioeconomico',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estrato_socioeconomico',
                'verbose_name_plural': 'Estratos_socioeconomicos',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_caso', models.PositiveIntegerField()),
                ('fecha_registro', models.DateField()),
                ('caso_gratuito', models.BooleanField(blank=True, default=True, null=True)),
                ('asunto_juridico_definible', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('expediente_pre_cerrado', models.BooleanField(blank=True, default=False, null=True)),
                ('expediente_cerrado', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Grupo_etnico',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Grupo_etnico',
                'verbose_name_plural': 'Grupos_etnicos',
            },
        ),
        migrations.CreateModel(
            name='Inicio_conflicto',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Inicio_conflicto',
                'verbose_name_plural': 'Inicios_conflicto',
            },
        ),
        migrations.CreateModel(
            name='Objetivo_servicio',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Objetivo_servicio',
                'verbose_name_plural': 'Objetivos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiExpedientesApp.area')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_expediente',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_cliente',
                'verbose_name_plural': 'Tipos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Solicitante_servicio',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Solicitante_servicio',
                'verbose_name_plural': 'Solicitantes_servicio',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cargo',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_cargo',
                'verbose_name_plural': 'Tipos_cargo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_cliente',
                'verbose_name_plural': 'Tipos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Tipo_discapacidad',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_Discapacidad',
                'verbose_name_plural': 'Tipos_Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_documento',
                'verbose_name_plural': 'Tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_persona',
                'verbose_name_plural': 'Tipos_persona',
            },
        ),
        migrations.CreateModel(
            name='Tipo_vivienda',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_vivienda',
                'verbose_name_plural': 'Tipos_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('Objetivo_servicio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.objetivo_servicio')),
            ],
            options={
                'verbose_name': 'Tipo_servicio',
                'verbose_name_plural': 'Tipos_servicio',
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tema')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25, unique=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=25)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=25, null=True)),
                ('apoderado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.apoderado')),
                ('datos_estudio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.datos_estudio')),
                ('escolaridad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.escolaridad')),
                ('estado_civil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_civil')),
                ('estrato_socioeconomico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estrato_socioeconomico')),
                ('genero_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.genero')),
                ('grupo_etnico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.grupo_etnico')),
                ('perfil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.perfil')),
                ('sexo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.sexo')),
                ('tipo_cargo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cargo')),
                ('tipo_discapacidad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_discapacidad')),
                ('tipo_documento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento')),
                ('tipo_persona_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_persona')),
                ('tipo_vivienda_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_vivienda')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pais')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('pais_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pais')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('localidad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pais')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.AddField(
            model_name='apoderado',
            name='tipo_documento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento'),
        ),
    ]
