# Generated by Django 4.1.3 on 2022-12-10 15:13

import apiExpedientesApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centro_conciliacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Centro_conciliacion',
                'verbose_name_plural': 'Centros_conciliacion',
                'db_table': 'Centro_conciliacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Ciudad',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado_solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_solicitud',
                'verbose_name_plural': 'Estados_solicitud',
                'db_table': 'Estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estrato_socioeconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'estratos_socioeconomicos',
                'verbose_name_plural': 'estratos_socioeconomicos',
                'db_table': 'Estrato_socioeconomico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'Genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'Pais',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'Sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_cliente',
                'verbose_name_plural': 'Tipos_cliente',
                'db_table': 'Tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_documento',
                'verbose_name_plural': 'Tipos_documento',
                'db_table': 'Tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_persona',
                'verbose_name_plural': 'Tipos_persona',
                'db_table': 'Tipo_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25)),
                ('lugar_expedicion', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(max_length=25)),
                ('tipo_documento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'db_table': 'Apoderado_expediente',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'Barrio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('consecutivo_actual', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Categoria_resultado',
                'verbose_name_plural': 'Categorias _resultado',
                'db_table': 'Categoria_resultado',
            },
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('enlace', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_sesion', models.DateField()),
            ],
            options={
                'verbose_name': 'Citacion',
                'verbose_name_plural': 'Citaciones',
                'db_table': 'Citacion',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'Encuesta',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
                'db_table': 'Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_civil',
                'verbose_name_plural': 'Estados_civiles',
                'db_table': 'Estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Estado_expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados_expediente',
                'db_table': 'Estado_expediente',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('identificador_sicaac', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_radicado', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_caso', models.CharField(default=apiExpedientesApp.models.increment_numero_caso_number, editable=False, max_length=25, unique=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('caso_gratuito', models.BooleanField(blank=True, default=True, null=True)),
                ('asunto_juridico_definible', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('expediente_pre_cerrado', models.BooleanField(blank=True, default=False, null=True)),
                ('expediente_cerrado', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'Expediente',
            },
        ),
        migrations.CreateModel(
            name='Finalidad_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'finalidad_servicio',
                'verbose_name_plural': 'finalidades_servicio',
                'db_table': 'finalidad_servicio',
            },
        ),
        migrations.CreateModel(
            name='Grupo_etnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo_etnico',
                'verbose_name_plural': 'Grupos_etnicos',
                'db_table': 'Grupo_etnico',
            },
        ),
        migrations.CreateModel(
            name='Inicio_conflicto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Inicio_conflicto',
                'verbose_name_plural': 'Inicios_conflicto',
                'db_table': 'Inicio_conflicto',
            },
        ),
        migrations.CreateModel(
            name='Medio_conocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Medio_conocimiento',
                'verbose_name_plural': 'Medios_conocimiento',
                'db_table': 'Medio_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Medio_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Medio_seguimiento',
                'verbose_name_plural': 'Medios_seguimiento',
                'db_table': 'Medio_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Objetivo_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Objetivo_servicio',
                'verbose_name_plural': 'Objetivos_servicio',
                'db_table': 'Objetivo_servicio',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiExpedientesApp.area')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=25)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=120)),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=25, null=True)),
                ('apoderado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.apoderado')),
                ('barrio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.barrio')),
                ('ciudad_nacimiento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad')),
                ('escolaridad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.escolaridad')),
                ('estado_civil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_civil')),
                ('estrato_socioeconomico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estrato_socioeconomico')),
                ('genero_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.genero')),
                ('grupo_etnico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.grupo_etnico')),
                ('perfil_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.perfil')),
                ('sexo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.sexo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pregunta_encuesta',
                'verbose_name_plural': 'Preguntas_encuesta',
                'db_table': 'Pregunta_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta_seguimiento',
                'verbose_name_plural': 'Preguntas_seguimiento',
                'db_table': 'Pregunta_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Solicitante_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Solicitante_servicio',
                'verbose_name_plural': 'Solicitantes_servicio',
                'db_table': 'Solicitud_servicio',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'Tema',
            },
        ),
        migrations.CreateModel(
            name='Tipo_cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_cargo',
                'verbose_name_plural': 'Tipos_cargo',
                'db_table': 'Tipo_cargo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_discapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_Discapacidad',
                'verbose_name_plural': 'Tipos_Discapacidad',
                'db_table': 'Tipo_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Tipo_medio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_medio',
                'verbose_name_plural': 'Tipos_medio',
                'db_table': 'Tipo_medio',
            },
        ),
        migrations.CreateModel(
            name='Tipo_reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_reporte',
                'verbose_name_plural': 'Tipos_reporte',
                'db_table': 'Tipo_reporte',
            },
        ),
        migrations.CreateModel(
            name='Tipo_vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_vivienda',
                'verbose_name_plural': 'Tipos_vivienda',
                'db_table': 'Tipo_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'Turno',
            },
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('Objetivo_servicio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.objetivo_servicio')),
            ],
            options={
                'verbose_name': 'Tipo_servicio',
                'verbose_name_plural': 'Tipos_servicio',
                'db_table': 'Tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='Tipo_resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.categoria_resultado')),
            ],
            options={
                'verbose_name': 'Tipo_resultado',
                'verbose_name_plural': 'Tipos_resultado',
                'db_table': 'Tipo_resultado',
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tema')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
                'db_table': 'Subtema',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('recomendacion_al_usuario', models.TextField(blank=True, null=True)),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('medio_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_seguimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('consecutivo', models.PositiveIntegerField()),
                ('acuerdo', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='resultados/')),
                ('fecha', models.DateField(auto_now=True)),
                ('expediente_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('tipo_resultado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_resultado')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'Resultado',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_seguimiento',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('si_o_no', models.BooleanField()),
                ('porque', models.TextField(blank=True, null=True)),
                ('pregunta_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_seguimiento')),
                ('seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.seguimiento')),
            ],
            options={
                'verbose_name': 'Respuesta_seguimiento',
                'verbose_name_plural': 'Respuestas_seguimiento',
                'db_table': 'Respuesta_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('encuesta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.encuesta')),
                ('pregunta_encuesta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta_encuesta',
                'verbose_name_plural': 'Respuestas_encuesta',
                'db_table': 'Respuesta_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona')),
                ('tipo_cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cliente')),
            ],
            options={
                'verbose_name': 'Relacion_persona_expediente',
                'verbose_name_plural': 'Relaciones_persona_expediente',
                'db_table': 'Relacion_persona_expediente',
                'ordering': ['-expediente_id'],
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('citacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.citacion')),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona')),
            ],
            options={
                'verbose_name': 'Relacion_persona_citacion',
                'verbose_name_plural': 'Relaciones_persona_citacion',
                'db_table': 'Relacion_persona_citacion',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_cargo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cargo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_discapacidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_discapacidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_documento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_documento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vivienda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_vivienda'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuarioId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidad',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_expediente')),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
                'db_table': 'Historico',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('cuantia_indeterminada', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_interviene_tercero', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_violencia', models.BooleanField(blank=True, default=False, null=True)),
                ('cuantia', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('Flag_conflicto_por_incapacidad', models.BooleanField(blank=True, default=False, null=True)),
                ('pretension', models.TextField(blank=True, null=True)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_resultado')),
                ('expediente_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Hechos',
                'verbose_name_plural': 'Hechos',
                'db_table': 'Hechos_expediente',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='Finalidad_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.finalidad_servicio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.area'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_expediente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_expediente'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='inicio_conflicto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.inicio_conflicto'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitante_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.solicitante_servicio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='subtema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.subtema'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_servicio'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='expediente_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='medio_conocimiento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_conocimiento'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='expediente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='tipo_medio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_medio'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='turno_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.turno'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='localidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.localidad'),
        ),
    ]
