# Generated by Django 4.1.3 on 2023-01-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('codigo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Codigo',
                'verbose_name_plural': 'Codigos',
                'db_table': 'Codigo',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
