# Generated by Django 4.0.4 on 2022-11-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='año',
            field=models.PositiveSmallIntegerField(default=2022),
        ),
    ]
