# Generated by Django 4.1.3 on 2022-11-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expediente',
            constraint=models.UniqueConstraint(fields=('numero_caso', 'fecha_registro'), name='caso_por_fecha'),
        ),
    ]
