# Generated by Django 4.1.3 on 2023-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
