# Generated by Django 4.0.4 on 2022-11-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='Estado_expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_expediente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado_expediente'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='identificacion',
            field=models.CharField(max_length=25),
        ),
    ]
