# Generated by Django 4.0.4 on 2022-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0002_rename_estado_estado_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
