# Generated by Django 4.1.3 on 2023-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0002_alter_tema_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta_encuesta',
            name='nombre',
            field=models.TextField(),
        ),
    ]
