# Generated by Django 4.1.3 on 2022-11-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0002_expediente_caso_por_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('acuerdo', models.TextField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='resultados/')),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Tipo_resultado',
            fields=[
                ('estado', models.BooleanField(blank=True, default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('consecutivo_actual', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Tipo_resultado',
                'verbose_name_plural': 'Tipos_resultado',
            },
        ),
        migrations.AlterModelOptions(
            name='relacion_persona_expediente',
            options={'verbose_name': 'Relacion_persona_expediente', 'verbose_name_plural': 'Relaciones_persona_expediente'},
        ),
        migrations.AddField(
            model_name='expediente',
            name='area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.area'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='inicio_conflicto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.inicio_conflicto'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitante_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.solicitante_servicio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='subtema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.subtema'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_servicio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_servicio'),
        ),
        migrations.AddField(
            model_name='relacion_persona_expediente',
            name='expediente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='relacion_persona_expediente',
            name='persona_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona'),
        ),
        migrations.AddField(
            model_name='relacion_persona_expediente',
            name='tipo_cliente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_cliente'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.estado')),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
            },
        ),
    ]
