# Generated by Django 4.0.4 on 2022-11-18 18:10

import apiExpedientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0002_alter_expediente_año'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expediente',
            name='caso_por_año',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='año',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_caso',
            field=models.PositiveIntegerField(default=apiExpedientesApp.models.increment_numero_caso_number),
        ),
    ]
