# Generated by Django 4.1.3 on 2023-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0003_alter_pregunta_encuesta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtema',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
