# Generated by Django 4.0.4 on 2022-11-29 16:20

import apiExpedientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0003_alter_expediente_numero_radicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_caso',
            field=models.CharField(default=apiExpedientesApp.models.increment_numero_caso_number, editable=False, max_length=22, unique=True),
        ),
    ]
