# Generated by Django 4.1.3 on 2022-11-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0003_estado_resultado_tipo_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='expediente_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='tipo_resultado_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_resultado'),
        ),
    ]
