# Generated by Django 4.0.4 on 2022-11-18 18:26

import apiExpedientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0003_remove_expediente_caso_por_año_remove_expediente_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_caso',
            field=models.CharField(default=apiExpedientesApp.models.increment_numero_caso_number, max_length=10),
        ),
    ]
