# Generated by Django 4.0.4 on 2022-11-29 16:50

import apiExpedientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0004_alter_expediente_numero_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_caso',
            field=models.CharField(default=apiExpedientesApp.models.increment_numero_caso_number, editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=25),
        ),
    ]
