# Generated by Django 4.1.3 on 2022-11-25 17:18

import apiExpedientesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0004_alter_expediente_numero_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_caso',
            field=models.CharField(default=apiExpedientesApp.models.increment_numero_caso_number, editable=False, max_length=10, unique=True),
        ),
    ]
