# Generated by Django 4.1.3 on 2022-11-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0004_resultado_expediente_id_resultado_tipo_resultado_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('enlace', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_sesion', models.DateField()),
            ],
            options={
                'verbose_name': 'Citacion',
                'verbose_name_plural': 'Citaciones',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Medio_conocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medio_conocimiento',
                'verbose_name_plural': 'Medios_conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Medio_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medio_seguimiento',
                'verbose_name_plural': 'Medios_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pregunta_encuesta',
                'verbose_name_plural': 'Preguntas_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Pregunta_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta_seguimiento',
                'verbose_name_plural': 'Preguntas_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_medio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_medio',
                'verbose_name_plural': 'Tipos_medio',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AlterField(
            model_name='expediente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('fecha', models.DateField()),
                ('expediente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
                ('medio_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_seguimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('si_o_no', models.BooleanField()),
                ('porque', models.TextField(blank=True, null=True)),
                ('pregunta_seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_seguimiento')),
                ('seguimiento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.seguimiento')),
            ],
            options={
                'verbose_name': 'Respuesta_seguimiento',
                'verbose_name_plural': 'Respuestas_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('encuesta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.encuesta')),
                ('pregunta_encuesta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.pregunta_encuesta')),
            ],
            options={
                'verbose_name': 'Respuesta_encuesta',
                'verbose_name_plural': 'Respuestas_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Relacion_persona_citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('citacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.citacion')),
                ('persona_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona')),
            ],
            options={
                'verbose_name': 'Relacion_persona_citacion',
                'verbose_name_plural': 'Relaciones_persona_citacion',
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('cuantia_indeterminada', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_interviene_tercero', models.BooleanField(blank=True, default=False, null=True)),
                ('flag_violencia', models.BooleanField(blank=True, default=False, null=True)),
                ('cuantia', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('Flag_conflicto_por_incapacidad', models.BooleanField(blank=True, default=False, null=True)),
                ('pretension', models.TextField(blank=True, null=True)),
                ('expediente_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente')),
            ],
            options={
                'verbose_name': 'Hechos',
                'verbose_name_plural': 'Hechos',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='expediente_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='medio_conocimiento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.medio_conocimiento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='persona_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.persona'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='expediente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.expediente'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='tipo_medio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.tipo_medio'),
        ),
        migrations.AddField(
            model_name='citacion',
            name='turnos_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.turno'),
        ),
    ]
