# Generated by Django 4.0.4 on 2022-11-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0005_alter_expediente_numero_caso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion_persona_expediente',
            name='nombre',
        ),
    ]
