# Generated by Django 4.1.3 on 2022-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0005_expediente_numero_radicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(max_length=20),
        ),
    ]
