# Generated by Django 4.1.3 on 2022-11-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0005_citacion_encuesta_medio_conocimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_reporte',
                'verbose_name_plural': 'Tipos_reporte',
            },
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='ciudad_id',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.departamento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.barrio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='localidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.localidad'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='ciudad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiExpedientesApp.ciudad'),
        ),
    ]
