# Generated by Django 4.1.3 on 2022-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0006_alter_expediente_numero_radicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_radicado',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
