# Generated by Django 4.1.3 on 2022-11-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0009_alter_area_nombre_alter_ciudad_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='barrio',
            new_name='barrio_id',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='ciudad_nacimiento',
            new_name='ciudad_nacimiento_id',
        ),
    ]
