# Generated by Django 4.1.3 on 2022-11-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0010_rename_barrio_persona_barrio_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='escolaridad_id',
        ),
        migrations.DeleteModel(
            name='Escolaridad',
        ),
    ]
