# Generated by Django 4.1.3 on 2022-11-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiExpedientesApp', '0011_remove_persona_escolaridad_id_delete_escolaridad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_estudio',
            new_name='Escolaridad',
        ),
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['-id'], 'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['-id'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='escolaridad',
            options={'verbose_name': 'Escolaridad', 'verbose_name_plural': 'Escolaridades'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['-id'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['-id'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='datos_estudio_id',
            new_name='escolaridad_id',
        ),
    ]
