# Generated by Django 4.1.3 on 2023-03-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
                'db_table': 'Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_civil',
                'verbose_name_plural': 'Estados_civiles',
                'db_table': 'Estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Grupo_etnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo_etnico',
                'verbose_name_plural': 'Grupos_etnicos',
                'db_table': 'Grupo_etnico',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'Tema',
            },
        ),
        migrations.CreateModel(
            name='Tipo_discapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_Discapacidad',
                'verbose_name_plural': 'Tipos_Discapacidad',
                'db_table': 'Tipo_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Tipo_vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo_vivienda',
                'verbose_name_plural': 'Tipos_vivienda',
                'db_table': 'Tipo_vivienda',
            },
        ),
        migrations.AddField(
            model_name='hechos_solicitud',
            name='pretension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='persona_ugc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='tarjeta_profesional',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='apellidos',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='nombres',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='tipo_documento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.tipo_documento'),
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=210)),
                ('tema_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.tema')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
                'db_table': 'Subtema',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.ciudad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidad',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=80)),
                ('localidad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.localidad')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'Barrio',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='barrio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.barrio'),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='escolaridad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.escolaridad'),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='estado_civil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.estado_civil'),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='grupo_etnico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.grupo_etnico'),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='tipo_discapacidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.tipo_discapacidad'),
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='tipo_vivienda_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.tipo_vivienda'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.area'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='subtema_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.subtema'),
        ),
    ]
