# Generated by Django 4.1.3 on 2022-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona_solicitud',
            name='ciudad_nacimiento_id',
        ),
        migrations.AddField(
            model_name='persona_solicitud',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
