# Generated by Django 4.0.4 on 2022-11-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='nuero_radicado',
            new_name='numero_radicado',
        ),
    ]
