# Generated by Django 4.1.3 on 2023-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
