# Generated by Django 4.0.4 on 2022-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
