# Generated by Django 4.1.3 on 2023-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0002_alter_persona_solicitud_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_solicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
