# Generated by Django 4.0.4 on 2022-11-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0002_alter_documento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion_persona_solicitud',
            name='nombre',
        ),
    ]
