# Generated by Django 4.1.3 on 2023-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0002_area_escolaridad_estado_civil_grupo_etnico_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_solicitud',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='nombres',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
