# Generated by Django 4.1.3 on 2023-01-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0002_solicitud_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='codigo',
        ),
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('solicitud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.solicitud')),
            ],
            options={
                'verbose_name': 'tabla',
                'verbose_name_plural': 'tabla',
            },
        ),
    ]
