# Generated by Django 4.1.3 on 2022-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0002_remove_persona_solicitud_ciudad_nacimiento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado_solicitud',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
