# Generated by Django 4.0.4 on 2022-11-18 06:05

import apiSolicitudesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0003_alter_solicitud_numero_radicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numero_radicado',
            field=models.CharField(default=apiSolicitudesApp.models.increment_entrada_number, max_length=25, primary_key=True, serialize=False),
        ),
    ]
