# Generated by Django 4.1.3 on 2023-01-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0003_remove_solicitud_codigo_tabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tabla',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='tabla',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
