# Generated by Django 4.0.4 on 2022-11-20 01:37

import apiSolicitudesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0004_solicitud_estado_alter_documento_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrato_socioeconomico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'estratos_socioeconomicos',
                'verbose_name_plural': 'estratos_socioeconomicos',
            },
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numero_radicado',
            field=models.CharField(default=apiSolicitudesApp.models.increment_entrada_number, editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
