# Generated by Django 4.1.3 on 2023-01-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0004_remove_tabla_estado_remove_tabla_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla',
            options={'verbose_name': 'tabla', 'verbose_name_plural': 'tablas'},
        ),
    ]
