# Generated by Django 4.0.4 on 2022-11-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0004_remove_documento_solicitud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='solicitud_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.solicitud'),
        ),
    ]
