# Generated by Django 4.0.4 on 2022-11-20 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0005_estrato_socioeconomico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estrato_socioeconomico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.estrato_socioeconomico'),
        ),
    ]
