# Generated by Django 4.0.4 on 2022-11-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0005_documento_solicitud_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado_solicitud',
                'verbose_name_plural': 'Estados_solicitud',
            },
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.estado_solicitud'),
        ),
    ]
