# Generated by Django 4.0.4 on 2022-11-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0006_estado_solicitud_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_conciliacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Centro_conciliacion',
                'verbose_name_plural': 'Centros_conciliacion',
            },
        ),
    ]
