# Generated by Django 4.1.3 on 2023-01-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0006_rename_tabla_codigo_alter_codigo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['-id'], 'verbose_name': 'Codigo', 'verbose_name_plural': 'Codigos'},
        ),
        migrations.AlterModelTable(
            name='codigo',
            table='Codigo',
        ),
    ]
