# Generated by Django 4.0.4 on 2022-11-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0006_persona_estrato_socioeconomico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='identificacion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=25),
        ),
    ]
