# Generated by Django 4.0.4 on 2022-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0008_alter_persona_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='id',
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='identificacion',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
