# Generated by Django 4.1.3 on 2023-01-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0008_codigo_estado_alter_codigo_codigo_alter_codigo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_solicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='estrato_socioeconomico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.estrato_socioeconomico'),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='genero_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.genero'),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='sexo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.sexo'),
        ),
        migrations.AlterField(
            model_name='persona_solicitud',
            name='tipo_persona_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiSolicitudesApp.tipo_persona'),
        ),
    ]
