# Generated by Django 4.0.4 on 2022-11-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0008_localidad_barrio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Persona_solicitud',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='ciudad_id',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
