# Generated by Django 4.0.4 on 2022-11-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0009_rename_persona_persona_solicitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='estado_solicitud',
            new_name='estado_solicitud_id',
        ),
    ]
