# Generated by Django 4.1.3 on 2023-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitudesApp', '0009_alter_persona_solicitud_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado_solicitud',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
