# Generated by Django 4.0.4 on 2022-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDocumentosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
