# Generated by Django 4.1.3 on 2023-02-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDocumentosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(blank=True, default='nombre', max_length=150),
        ),
    ]
